25/connect cart to back end
tknura/2021_BD2_S15_WYLEGLY-UI pull request #36
Opened 2021-06-16 16:41 UTC by PatrykLipka

cart back-end connection with usage of context to maintain data even without being logged in

2021-06-20 19:58 UTC, tknura requested changes

2021-06-20 19:58 UTC, tknura commented on src/components/data/CartItemArea/CartItemArea.tsx
> +interface CartItemResponse {
`CartItem` było okej, jesteś w komponencie = w tym miejscu Response cie nie obchodzi, otypowujesz element wyswietlany

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +import { useAddCartItemMutation, useDeleteCartItemMutation, useEditCartItemMutation, useGetCartItemsQuery, useSubmitCartMutation } from 'api/cart'
przy takiej dużej ilości importy odzielać enterem: 
```
import {
  useAddCartItemMutation,
  useDeleteCartItemMutation,
  useEditCartItemMutation,
  useGetCartItemsQuery,
  useSubmitCartMutation
} from 'api/cart'
```

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +interface CartItemResponse {
tutaj też `CartItem` jest lepszą nazwą

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +  const [missingBooksError, setMissingBooksError] = useState<string | undefined>()
jak nie ma błędu to powinno być `null`, `undefined` jest zarezerwone dal zmiennych które jeszcze nie zostały zaincjalizowane, dostanie undefined runtime ma sygnalizować błąd w programie a nie świadome działanie (null jest po prostu lepszą praktyką)

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +      setMissingBooksError(undefined)
`null` zamiast `undefined`

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +      show({ message: t('screen.signIn.errors.generic'), type: SNACKBAR_ERROR })
skoro wyświetlamy missing books w modalu, to wyświetalnie generycznego błędu (jeszcze w dodatku z ekranu signIn) nie jest potrzebne

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +      setMissingBooksError(undefined)
ogółem wydaje mi się że linia jest zbędna

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +        cartItems: cartData,
mam wątpliwości czy to zadziała, musiałbyś w tym miejscu po prostu wywoływać pobieranie danych z `useGetCartItemsQuery` na nowo (sterowanie parametrem `enabled`). W ten sposób jak to aktualnei jest zrobione po poprawnym dodaniu/edycji/usunięciu ustawi ci po prostu stare dane, będzie wyglądało jakby sie nic nie działo

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +    },
tak samo jak wyżej, zamiast ustawiać stan w ten sposób po prostu spraw by wykonał się refetch query (zmienna enabled)

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +      })
tak samo jak wyżej, zamiast ustawiać stan w ten sposób po prostu spraw by wykonał się refetch query (zmienna enabled)

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +      })
zamiast `forEach` lepszy `map`

2021-06-20 19:58 UTC, tknura commented on src/screens/CartScreen/CartScreen.tsx
> +    setMissingBooks(missingBooksError)
niepotrzebne, wystarczy bazować na `missingBooksError`

2021-06-20 19:58 UTC, tknura commented on src/screens/CartScreen/CartScreen.tsx
> +interface CartItemResponse {
w tym przypadku nie musisz na nowo redefiniować interfejsu, wystarczy że zaimportujesz go z `CartItemArea`, bo do jego handlerów wykorzystujesz ten typ

2021-06-20 19:58 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +      const newItems = cart?.cartItems?.concat(item)
lepiej jest zrobić coś takiego:
```
const newItems = [...cart?.cartItems, item]
```
zgodniejsze z nowszym standardem js - ES6

2021-06-20 22:49 UTC, PatrykLipka commented on src/components/providers/CartProvider.tsx
> +      const newItems = cart?.cartItems?.concat(item)
else if (cart?.cartItems) {
      const newItems = [...cart?.cartItems, item]

musiałem dodać if, nie mam pewności czy to miałeś na myśli

2021-06-21 14:02 UTC, tknura commented on src/components/providers/CartProvider.tsx
> +      const newItems = cart?.cartItems?.concat(item)
generalnie podwójny nulish operator (? przed .) to 🧀 więc ten if nawet wskazany

2021-06-21 21:22 UTC, tknura approved these changes

2021-06-22 09:32 UTC, merged